apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "dp-kafka-connect-apply"
  namespace: "teamdagpenger"
  labels:
    "team": "teamdagpenger"
spec:
  image: {{image}}
  port: 3000
  replicas:
    max: 1
    min: 1
    disableAutoScaling: true
  prometheus:
    enabled: false
  env:
    - name: GCP_PROJECT
      value: {{gcp.project}}
    - name: CONNECTORS
      value: /connectors
    - name: KAFKA_CONNECT
      value: http://dp-kafka-connect:8083
  filesFrom:
    - configmap: dp-kafka-connect-connectors
      mountPath: /connectors
  accessPolicy:
    outbound:
      rules:
        - application: dp-kafka-connect